# Generated by Django 6.0.3 on 2026-03-07 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
        ('accounts', '0002_seed_admin_user'),
    ]

    operations = [
    ]
