# Generated by Django 6.0.3 on 2026-03-07 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_fix_admin_password'),
        ('accounts', '0003_merge_0002_alter_user_managers_0002_seed_admin_user'),
    ]

    operations = [
    ]
