# Generated by Django 6.0.3 on 2026-03-07 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_vehiclecategory_alter_driverprofile_vehicle_type_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='vehicle_requested',
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_weight',
            field=models.IntegerField(default=0, help_text='Weight in kg'),
        ),
        migrations.AddField(
            model_name='order',
            name='goods_type',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='drivers.vehiclecategory'),
        ),
        migrations.AlterField(
            model_name='order',
            name='package_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
