# Generated by Django 6.0.3 on 2026-03-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_dropoff_lat_order_dropoff_lng_order_pickup_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dropoff_lat',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='dropoff_lng',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_lat',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_lng',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
    ]
