# Generated by Django 6.0.3 on 2026-03-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_dropoff_lat_alter_order_dropoff_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
