# Generated by Django 6.0.3 on 2026-03-07 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_docs', 'Pending Documents'), ('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], default='pending_docs', max_length=25)),
                ('vehicle_type', models.CharField(blank=True, choices=[('bike', 'Bike'), ('mini_truck', 'Mini Truck'), ('pickup', 'Pickup'), ('large_truck', 'Large Truck')], max_length=20, null=True)),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('license_document', models.FileField(blank=True, null=True, upload_to='driver_docs/')),
                ('insurance_document', models.FileField(blank=True, null=True, upload_to='driver_docs/')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('is_online', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
