# Generated by Django 6.0.3 on 2026-03-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('2_wheeler', '2-Wheeler (Bike/Scooter)'), ('3_wheeler', '3-Wheeler (Auto/Rickshaw)'), ('tata_ace', 'Tata Ace (Chota Hathi)'), ('pickup', 'Pickup/Bolero'), ('truck_7ft', '7ft Truck'), ('truck_14ft', '14ft Truck'), ('truck_19ft', '19ft Truck'), ('truck_32ft', '32ft Truck')], max_length=20, null=True),
        ),
    ]
