# Generated by Django 6.0.3 on 2026-03-07 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_alter_driverprofile_vehicle_type'),
        ('drivers', '0002_driverprofile_status_reason'),
    ]

    operations = [
    ]
