# Generated by Django 6.0.3 on 2026-03-07 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driverprofile_is_reapplied_driverprofile_updated_at'),
        ('drivers', '0003_merge_20260308_0106'),
    ]

    operations = [
    ]
