# Generated by Django 6.0.3 on 2026-03-07 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_seed_vehicle_categories'),
        ('drivers', '0005_vehiclecategory_alter_driverprofile_vehicle_type_and_more'),
    ]

    operations = [
    ]
